export const THUMBNAIL_IMAGES = [
  {
    path: "/getup",
    src: "/images/img 1.jpg",
    alt: "img-1",
    date: "21 / 07 / 2022",
    title: "Get Up Bali",
  },
  {
    path: "/",
    src: "/images/img 2.jpg",
    alt: "img-2",
    date: "21 / 07 / 2022",
    title: "Thank God It's Festival",
  },
  {
    path: "/",
    src: "/images/img 3.jpg",
    alt: "img-3",
    date: "21 / 07 / 2022",
    title: "Kedungu Beach Festival",
  },
  {
    path: "/",
    src: "/images/img 4.jpg",
    alt: "img-4",
    date: "21 / 07 / 2022",
    title: "ALCO",
  },
  {
    path: "/",
    src: "/images/img 5.jpg",
    alt: "img-5",
    date: "21 / 07 / 2022",
    title: "ALCO",
  },
  {
    path: "/",
    src: "/images/img 6.jpg",
    alt: "img-6",
    date: "21 / 07 / 2022",
    title: "ALCO",
  },
  {
    path: "/",
    src: "/images/img 7.jpg",
    alt: "img-7",
    date: "21 / 07 / 2022",
    title: "ALCO",
  },
  {
    path: "/",
    src: "/images/img 8.jpg",
    alt: "img-8",
    date: "21 / 07 / 2022",
    title: "Gemo Fest",
  },
  {
    path: "/",
    src: "/images/img 9.jpg",
    alt: "img-9",
    date: "21 / 07 / 2022",
    title: "Beer & Co",
  },
  {
    path: "/",
    src: "/images/img 10.jpg",
    alt: "img-10",
    date: "21 / 07 / 2022",
    title: "Univlox",
  },
];
